import Head from "next/head";
import Image from "next/image";
import { Work_Sans } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/Components/Header";
import Services from "@/Components/Services";
import Skills from "@/Components/Skills";
import Projects from "@/Components/Projects";
import Blogs from "@/Components/Blogs";
import Contacts from "@/Components/Contacts";
import { Grid, Item } from "@mui/material";
import { Box } from "@mui/system";

const WorkSans = Work_Sans({ subsets: ["latin"], variable:'--font-sans' });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${WorkSans.variable} font-sans`}>
        <Box className={styles.main}>
          <Header />
          <Services />
          <Skills />
          <Projects />
          {/* <Blogs /> */}
          <Contacts />
        </Box>
      </main>
    </>
  );
}
